### ISSUE TITLE
Interactive WGLMakie figure throws errors

### ISSUE THREAD

**Issue by kbarros** [MakieOrg/Makie.jl#3781]
The test case that I currently have requires installing `Sunny`. When I execute this,

```julia
using Sunny, WGLMakie
cryst = Sunny.fcc_crystal()
view_crystal(cryst)
```

and then interact the the WGLMakie figure, it throws many "key not found" errors. Example stack trace below. I haven't had luck reducing this to a simpler standalone test case. When I starting remove things from the scene, the frequency of the errors decrease, in a seemingly nondeterministic way.

```
An exception was thrown in JS: Error: Key 25837 not found! undefined
Additional message: Error while processing message {"payload":false,"id":"25837","msg_type":"0"}
Stack trace:
    Error: Key 25837 not found! undefined
        at lookup_global_object (http://localhost:9384/assets/a3ea2b1768bae0eec7c90e59010978af2088e5c5-Bonito.bundled.js:3708:11)
        at Object.process_message (http://localhost:9384/assets/a3ea2b1768bae0eec7c90e59010978af2088e5c5-Bonito.bundled.js:3650:17)
        at http://localhost:9384/assets/439a543fe5196e6a836a7ad81e559b5ad3108dec-Websocket.bundled.js:95:32
        at http://localhost:9384/assets/a3ea2b1768bae0eec7c90e59010978af2088e5c5-Bonito.bundled.js:3638:33
        at new Promise (<anonymous>)
        at Lock.lock (http://localhost:9384/assets/a3ea2b1768bae0eec7c90e59010978af2088e5c5-Bonito.bundled.js:3632:16)
        at http://localhost:9384/assets/439a543fe5196e6a836a7ad81e559b5ad3108dec-Websocket.bundled.js:94:48
        at new Promise (<anonymous>)
        at websocket.onmessage (http://localhost:9384/assets/439a543fe5196e6a836a7ad81e559b5ad3108dec-Websocket.bundled.js:89:17)
┌ Warning: Error in window event callback
│   exception =
│    ArgumentError: collection must be non-empty
│    Stacktrace:
│     [1] first
│       @ ./abstractarray.jl:473 [inlined]
│     [2] (::Makie.var"#1441#1443"{Scene, Base.RefValue{Bool}, Base.RefValue{Union{Nothing, Makie.Mouse.Button}}, Base.RefValue{Float64}, Base.RefValue{Float64}, Base.RefValue{Bool}, Base.RefValue{Bool}, Base.RefValue{Union{Nothing, Makie.Mouse.Button}}, Base.RefValue{Bool}, Base.RefValue{Point{2, Float32}}, Base.RefValue{Point{2, Float32}}, Base.RefValue{Makie.Mouse.Action}, Observable{MouseEvent}, Float64, Module})(event::Makie.MouseButtonEvent)
│       @ Makie ~/.julia/dev/Makie/src/makielayout/mousestatemachine.jl:292
│     [3] #invokelatest#2
│       @ ./essentials.jl:892 [inlined]
│     [4] invokelatest
│       @ ./essentials.jl:889 [inlined]
│     [5] notify
│       @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [6] setindex!
│       @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123 [inlined]
│     [7] (::WGLMakie.var"#58#60"{Dict{Any, Any}, Scene, Events})()
│       @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:63
└ @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:109
┌ Warning: Error in window event callback
│   exception =
│    ArgumentError: collection must be non-empty
│    Stacktrace:
│     [1] first
│       @ ./abstractarray.jl:473 [inlined]
│     [2] (::Makie.var"#1441#1443"{Scene, Base.RefValue{Bool}, Base.RefValue{Union{Nothing, Makie.Mouse.Button}}, Base.RefValue{Float64}, Base.RefValue{Float64}, Base.RefValue{Bool}, Base.RefValue{Bool}, Base.RefValue{Union{Nothing, Makie.Mouse.Button}}, Base.RefValue{Bool}, Base.RefValue{Point{2, Float32}}, Base.RefValue{Point{2, Float32}}, Base.RefValue{Makie.Mouse.Action}, Observable{MouseEvent}, Float64, Module})(event::Makie.MouseButtonEvent)
│       @ Makie ~/.julia/dev/Makie/src/makielayout/mousestatemachine.jl:292
│     [3] #invokelatest#2
│       @ ./essentials.jl:892 [inlined]
│     [4] invokelatest
│       @ ./essentials.jl:889 [inlined]
│     [5] notify
│       @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│     [6] setindex!
│       @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123 [inlined]
│     [7] (::WGLMakie.var"#58#60"{Dict{Any, Any}, Scene, Events})()
│       @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:63
└ @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:109
```

**Comment by kbarros** [comment]
Here is another error that eventually appeared after a lot of interaction (but again, I can't easily reproduce...)
```
┌ Warning: Error in window event callback
│   exception =
│    type Nothing has no field attributes
│    Stacktrace:
│      [1] getproperty(x::Nothing, f::Symbol)
│        @ Base ./Base.jl:37
│      [2] (::Makie.var"#1320#1321"{DataInspector, Scene})()
│        @ Makie ~/.julia/dev/Makie/src/interaction/inspector.jl:307
│      [3] lock(f::Makie.var"#1320#1321"{DataInspector, Scene}, l::ReentrantLock)
│        @ Base ./lock.jl:229
│      [4] on_hover
│        @ ~/.julia/dev/Makie/src/interaction/inspector.jl:301 [inlined]
│      [5] (::Makie.var"#1312#1316"{DataInspector})(::Tuple{Float64, Float64})
│        @ Makie ~/.julia/dev/Makie/src/interaction/inspector.jl:281
│      [6] #invokelatest#2
│        @ ./essentials.jl:892 [inlined]
│      [7] invokelatest
│        @ ./essentials.jl:889 [inlined]
│      [8] notify
│        @ ~/.julia/packages/Observables/YdEbO/src/Observables.jl:206 [inlined]
│      [9] setindex!(observable::Observable, val::Any)
│        @ Observables ~/.julia/packages/Observables/YdEbO/src/Observables.jl:123
│     [10] (::WGLMakie.var"#58#60"{Dict{Any, Any}, Scene, Events})()
│        @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:57
└ @ WGLMakie ~/.julia/dev/Makie/WGLMakie/src/events.jl:112
```

**Comment by SimonDanisch** [comment]
For the first you should look in the js console if there's an error there.
For the second I have an idea!

**Comment by SimonDanisch** [comment]
Great! :) Best open a new issue with js console output etc, when something comes up again ;)
