### ISSUE TITLE
WebGL error: Invalid operation

### ISSUE THREAD

**Issue by jfb-h** [MakieOrg/Makie.jl#4355]
I have a Bonito/WGLMakie server running on a remote ubuntu machine (no GPU) and see a lot of this:

```
An exception was thrown in JS: Error: WebGL error: Invalid operation
Additional message: error initializing scene
Stack trace:
    Error: WebGL error: Invalid operation
        at eval (eval at <anonymous> (https://<my-domain>//assets/3ae30bea3b08484eeeb9c637b1977aa5a2265c17-Bonito.bundled.js:3561:27), <anonymous>:12:19)
```

It seems to still work mostly, although sometimes ticks or figure sizes don't update properly, but that might be unrelated.

I also see `ERROR: IOError: write: broken pipe (EPIPE)` HTTP errors every now and then, which also seem unrelated.

Bonito 3.2.0 and WGLMakie 0.10.10

**Comment by SimonDanisch** [comment]
Without something like an MWE, it's hard to have this as an actionable issue.

**Comment by jfb-h** [comment]
I'll try to find an MWE, I thought maybe the error had popped up before or it's a setup thing.

**Comment by jfb-h** [comment]
Ok so this (based on the example you posted on slack recently) reproduces the WebGL error for me:

```julia
using Bonito
using WGLMakie

app() = App() do session
    xy = Observable(Float64[100])

    fig = Figure()
    ax = Axis(fig[1, 1])

    Base.errormonitor(@async while true
        dat = rand(100)
        xy[] = dat
        autolimits!(ax)
        sleep(1)
        isopen(session) || break
    end)

    hist!(ax, xy)
    DOM.div(fig)
end

server = Server("<ip-addr>", 1234)
route!(server, "/test" => app())
server
```

```julia-repl
julia> An exception was thrown in JS: Error: WebGL error: Invalid operation
Additional message: error initializing scene
Stack trace:
    Error: WebGL error: Invalid operation
        at eval (eval at <anonymous> (http://<ip-addr>:1234/assets/3ae30bea3b08484eeeb9c637b1977aa5a2265c17-Bonito.bundled.js:3561:27), <anonymous>:12:19)
```
It only prints to the console but doesn't interrupt anything, so maybe its just safe to ignore it.

**Comment by SimonDanisch** [comment]
My browser actually returns some more info:
![image](https://github.com/user-attachments/assets/7a7ce6f3-d55b-498e-84f5-50955d48668d)

Maybe it's related to the first empty plot!
